"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$all"

[character]
format = "[󰘧](bold) "
success_symbol = "󰘧(bold green)"
error_symbol = "󰘧(bold red)"
vimcmd_symbol = "[V](bold green)"
